# Generated by Django 5.2.4 on 2025-08-05 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=1024, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время и дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время и дата изменения"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
            options={
                "verbose_name": "План обучения",
                "verbose_name_plural": "Планы обучения",
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, max_length=1024, null=True, verbose_name="Описание"
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Порядковый номер")),
                (
                    "estimated_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Расчетное количество дней"
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(default=False, verbose_name="Обязательность"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="studyhub.plan",
                        verbose_name="План обучения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тема обучения",
                "verbose_name_plural": "Темы обучения",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "is_done",
                    models.BooleanField(default=False, verbose_name="Выполняемость"),
                ),
                (
                    "estimated_minutes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Расчетное время (в минутах)",
                    ),
                ),
                (
                    "actual_minutes",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Фактическое время (в минутах)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время и дата создания"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="studyhub.topic",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача темы обучения",
                "verbose_name_plural": "Задачи темы обучения",
            },
        ),
    ]
